# Site settings
title: Welcome to Swift Crypto LLC
email: swiftcryptollc@gmail.com
url: https://swiftcryptollc.github.io
description: >-
  A crypto mining small business based in Leesburg VA.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'

# Footer settings
footer: Swift Crypto LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, twitter facebook stack-overflow, bitbucket, etc.)
social:
  - title: reddit
    url: https://www.reddit.com/user/SwiftCryptoLLC/
  - title: facebook
    url: https://www.facebook.com/Swift-Crypto-LLC
  - title: twitter
    url: https://twitter.com/SwiftCryptoLLC
  - title: linkedin
    url: https://www.linkedin.com/company/swift-crypto-llc
  - title: telegram
    url: https://t.me/SwiftCryptoLLC
  - title: github
    url: https://github.com/swiftcryptollc

include:
  - tools
  
# Build settings
markdown: kramdown
permalink: pretty
